language: python
python: '3.6'
sudo: required
dist: trusty
install:
- pip install --upgrade pip wheel setuptools
- pip install virtualenv tox
script:
- tox
env:
  matrix:
  - TOXENV=py27-django1.11
  - TOXENV=py34-django1.11
  - TOXENV=py35-django1.11
  - TOXENV=py36-django1.11
  - TOXENV=py34-django2.0
  - TOXENV=py35-django2.0
  - TOXENV=py36-django2.0
  - TOXENV=py35-django2.1
  - TOXENV=py36-django2.1
matrix:
  include:
  - python: '3.5'
    env: TOXENV=py35-django1.11
  exclude:
  - python: '3.6'
    env: TOXENV=py35-django1.11
  - python: '3.6'
    env: TOXENV=py35-django2.0
  - python: '3.6'
    env: TOXENV=py35-django2.1
